### PR TITLE
Fixed: The tags in this repo to be eligible for hacktoberfest

### PR DESCRIPTION
**Pull request by shivarm**
**Fixed the tags in this repo to be eligible for hacktoberfest.**

# issues: #47

# screenshort
Screenshot (172)

### CODE REVIEW

**Comment by sudipnext** [comment]
Since I think it's more like spam rather than a real contribution. So, I am marking this as invalid or spam because this repository is already eligible for Hacktoberfest.

**Comment by sudipnext** [comment]
Because our contributors have pending contribution timer on the official hacktoberfest site, who have contributed before now. If you still insist this is not spam then show some proof or something that's making this repo ineligible for hacktoberfest.

**Comment by shivam-sharma7** [comment]
first you check, I remove some extral line in README.md then I solve issue #47 as you can see above screenshot and this is it.

**Comment by proffapt** [comment]
@shivam-sharma7 you can't solve #47 , only the owners or full-access users of this repo can do it.

**Comment by sudipnext** [comment]
Sorry! For the inconvenience, My bad, but I can't merge this towards the contribution cause adding spaces will be equivalent to the spam on hacktoberfest, which is not suitable for your contributions towards this hacktoberfest. And plus I think the correct hacktoberfest2022 is doing its job of put this repo eligible for the hacktoberfest contribution.

**Review by proffapt — COMMENTED** [review]
You have just removed two lines, this violates the conditions of hacktoberfest.. thus it is a spam.

**Comment by shivam-sharma7** [comment]
> Sorry! For the inconvenience, My bad, but I can't merge this towards the contribution cause adding spaces will be equivalent to the spam on hacktoberfest, which is not suitable for your contributions towards this hacktoberfest. And plus I think the correct hacktoberfest2022 is doing its job of put this repo eligible for the hacktoberfest contribution.

okay @sudipnext

**Comment by proffapt** [comment]
> And plus I think the correct hacktoberfest2022 is doing its job of put this repo eligible for the hacktoberfest contribution.

no, it's because you label the pr with `hacktoberfest-accepted` label.

Now I see you have updated the tags.. cool

**Comment by sudipnext** [comment]
Okay, Huge thanks to you guys @shivam-sharma7  and @proffapt  I think will close the pull request now!

**Pull request closed without merging**
